### ISSUE TITLE
PS Vita: Can't Open In Game Menu

### ISSUE THREAD

**Issue by DerinQyu** [Cpasjuste/pfba#44]
On a PS Vita with 3.60 firmware; when you are inside a game pushing "select + start" won't trigger the emulator menu settings.

Tested on latest 1.57 from releases page.

**Comment by rsn8887** [comment]
You have to push Start + R now. It changed. It is better this way. Because Select + Start toggles the cheat menu in Neo Geo games with Unibios enabled.

I think the new buttons are:
`
Start + Triangle      : SERVICE SWITCH
Start + Circle      : 1P + 2P START
Start + R    : PFBA MENU
Start + Select      : UNIBIOS MENU (NEOGEO ONLY)
`
I might have gotten some wrong, you can just try a few combinations.

**Comment by DerinQyu** [comment]
Yes, you are right. I can get into the menu, thanks.

Gonna close this issue, but readme needs an update with new combinations so nobody will complain about this again.
